---
title: "Plotting_Scaffold"
author: "Grant Foster"
date: "2023-06-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(magrittr)
```

```{r}
load("mini_simulationNegative.Rda")
```

```{r}
x <- list_results[[1]]

plot(x$high$P_TraitVT_total)
```

```{r}
#str(list_results)

run1 <- list_results[[2]]
tail(run1$plants)

neutral_5 <- list_results
rm(list_results)
```

Counting successful runs
```{r}
index <- NULL
for(i in 1:100){
index <- c(index,list_results[[i]]$plants[1])
}
table(index)

which(index=="1")
```



Mean Niche Breadth
```{r}
plotPlantVariance <- function(list_results, title="plants"){
  index <- NULL
  for(i in 1:100){
    index <- c(index,list_results[[i]]$plants[1])
  }
table(index)
plot(x=1, y=1, xlab="time", ylab="Abundace-Weighted Mean Trait Variance", main=title, xlim=c(0,3001), ylim=c(0,0.2))
for(i in which(index=="1")){
  pcom_abund <- as.data.frame(list_results[[i]]$plants) %>% group_by(., V2) %>% summarize(., across(everything(), sum)) #create community abundance matrix by summing across sites (V2)
  
  WmeanVar <- apply(pcom_abund[,3:ncol(pcom_abund)]/rowSums(pcom_abund[,3:ncol(pcom_abund)]), MARGIN=1, FUN=function(X){ #Input into this function is the relative abundances of each species
    sum(X*list_results[[i]]$p_traitV) #multiply the mean trait value by relative abundances at each timestep, then return the sum
    }
  )
  points(x=1:length(WmeanVar), y=WmeanVar, type="l", xlab="time", col=alpha("black", alpha=0.25))
  }
}


plot(x=1, y=1, xlab="time", ylab="Abundace-Weighted Mean Trait Variance", main="Animals", xlim=c(0,3001), ylim=c(0,0.2))
for(i in which(index=="1")){
  acom_abund <- as.data.frame(list_results[[i]]$animals) %>% group_by(., V2) %>% summarize(., across(everything(), sum)) #create community abundance matrix by summing across sites (V2)
  
  WmeanVar <- apply(acom_abund[,3:ncol(acom_abund)]/rowSums(acom_abund[,3:ncol(acom_abund)]), MARGIN=1, FUN=function(X){ #Input into this function is the relative abundances of each species
    sum(X*list_results[[i]]$a_traitV) #multiply the mean trait value by relative abundances at each timestep, then return the sum
    }
  )
  points(x=1:length(WmeanVar), y=WmeanVar, type="l", xlab="time", col=alpha("black", alpha=0.25))
}

```

```{r}
plotPlantVariance(negative_5, title="Plants:Negative, 5 sites")
plotPlantVariance(neutral_5, title="Plants:Neutral, 5 sites")
plotPlantVariance(positive_5, title="Plants:Positive, 5 sites")
plotPlantVariance(neutral_15, title="Plants:Neutral, 15 sites")
plotPlantVariance(positive_15, title="Plants:Positive, 15 sites")
```


Who's successfully colonizing?
```{r}
colonization <- apply(pcom_abund[,3:ncol(pcom_abund)],2, function(x) pcom_abund$V2[x !=0][1])

extinction <- apply(pcom_abund[,3:ncol(pcom_abund)],2, function(x) tail(pcom_abund$V2[x !=0],1))

hist(extinction-colonization, breaks=12)

plot(y=run1$p_traitV, x=extinction-colonization)
```

Community vs Population Stability?
```{r}

```


```{r}
Positive_0 <- list_results
Neu_0 <- list_results
Neg_0 <- list_results

plot(x=1:1000, y=NULL, ylim=c(0,0.25), ylab="Mean Abundance-Weighted Trait Variance in Community", xlab="Time", main="Plants")
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$high$P_TraitVT_total)
}
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$med$P_TraitVT_total, col="blue")
}
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$low$P_TraitVT_total, col="red")
}


plot(x=1:1000, y=NULL, ylim=c(0,0.25), ylab="Mean Abundance-Weighted Trait Variance in Community", xlab="Time", main="Pollinators")
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$high$A_TraitVT_total)
}
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$med$A_TraitVT_total, col="blue")
}
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$low$A_TraitVT_total, col="red")
}
```


```{r}
plot(x=1:1000, y=NULL, ylim=c(0.05,0.25), ylab="Mean Abundance-Weighted Trait Variance in Community", xlab="Time", main="Plants")
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$med$P_TraitVT_total, col="dark green")
    lines(x=1:1000, y=Neg_0[[i]]$med$P_TraitVT_total, col="red")
    lines(x=1:1000, y=Neu_0[[i]]$med$P_TraitVT_total, col="brown")
}

plot(x=1:1000, y=NULL, ylim=c(0.05,0.25), ylab="Mean Abundance-Weighted Trait Variance in Community", xlab="Time", main="Pollinators"+)
for(i in 1:100){
  lines(x=1:1000, y=Positive_0[[i]]$med$A_TraitVT_total, col="dark green")
  lines(x=1:1000, y=Neu_0[[i]]$med$A_TraitVT_total, col="brown")
  lines(x=1:1000, y=Neg_0[[i]]$med$A_TraitVT_total, col="red")
}

```

